# This model has been trained on 8x GPUs, and only required about 6500MB of GPU memory per GPU.
model_name: RIM
dataset:
    name: FastMRI
    transforms:
        crop: [320, 320]
training:
    batch_size: 1
    optimizer: Adam
    lr: 0.005
    weight_decay: 0.0
    lr_step_size: 100000
    lr_gamma: 0.5
    lr_warmup_iter: 1000
    num_iterations: 500000
    gradient_steps: 1
    gradient_clipping: 0.0
    gradient_debug: false
    checkpointer:
        checkpoint_steps: 1000
    validation_steps: 1000
    loss:
        crop: [320, 320]
model:
    hidden_channels: 64
    length: 8
    depth: 2
    steps: 1
    invertible: false
    invertible_keep_step: 4
    no_parameter_sharing: false
    instance_norm: false
    dense_connect: false
    replication_padding: true
masking:
    name: FastMRI
    accelerations: [4]
    center_fractions: [0.08]
    val_accelerations: [4]
    val_center_fractions: [0.08]
