repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: forbid-new-submodules
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
