pep257:
  disable:
    - D203 # Conflict with numpydocs
    - D213 # Conflict with numpydocs
    - D212 # Conflict with numpydocs
pep8:
  disable:
    - E501 # Handled by black
    - W605 # Conflict with numpydocs - invalid escape sequence
pylint:
  disable:
    - import-outside-toplevel
  options:
    max-args: 20
