pep257:
  disable:
    - D203
    - D212
pep8:
  disable:
    - E501
    - W605

pylint:
  errors-only
  E
  options:
    errors-only
    E
    
pylintpython3:
  errors-only
  E
  options:
    errors-only
    E
  
