pep257:
  disable:
    - D203
    - D212
pep8:
  disable:
    - E501
    - W605

pylint:
#   errors-only: true
  disable:
    - too-many-arguments
  enable:
    - errors-only
  load-plugins:
    - errors-only
  
