# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.8

env:
  # - PYTORCH_CHANNEL=pytorch
  - PYTORCH_CHANNEL=pytorch-nightly

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing boost
  - conda install torchvision -c pytorch
    # TODO: Nightly is not always needed.
  - conda install torchvision cpuonly python=$TRAVIS_PYTHON_VERSION -c $PYTORCH_CHANNEL
  - conda install scipy pandas scikit-learn scikit-image=0.16 -yq
  - python -m pip install --pre omegaconf -q
  - python -m pip install pyxb
  - python -m pip install git+https://github.com/ismrmrd/ismrmrd-python.git
  - python setup.py install

# Command to run tests, e.g. python setup.py test
script: make test

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: directgroup
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: directgroup/direct
    python: 3.8



