physics:
    forward_operator: fft2
    backward_operator: ifft2
training:
    datasets:
        -   name: FastMRI
            filenames_lists:
                -   ../lists/train_10_coils.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip: true
                random_rotation: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
        -   name: FastMRI
            filenames_lists:
                -   ../lists/train_14_coils.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip: true
                random_rotation: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
        -   name: FastMRI
            filenames_lists:
                -   ../lists/train_16_coils.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip: true
                random_rotation: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
        -   name: FastMRI
            filenames_lists:
                -   ../lists/train_20_coils.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip: true
                random_rotation: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
        -   name: FastMRI
            filenames_lists:
                -   ../lists/train_24_coils.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip: true
                random_rotation: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
        -   name: FastMRI
            filenames_lists:
                -   ../lists/train_26_coils.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip: true
                random_rotation: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
        -   name: FastMRI
            filenames_lists:
                -   ../lists/train_30_coils.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip: true
                random_rotation: true
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
    batch_size: 2  # This is the batch size per GPU!
    optimizer: Adam
    lr: 0.002
    weight_decay: 0.0
    lr_step_size: 30000
    lr_gamma: 0.2
    lr_warmup_iter: 1000
    num_iterations: 500000
    gradient_steps: 1
    gradient_clipping: 0.0
    gradient_debug: false
    checkpointer:
        checkpoint_steps: 2000
    validation_steps: 4000
    loss:
        crop: header
        losses:
            -   function: l1_loss
                multiplier: 1.0
            -   function: ssim_loss
                multiplier: 1.0
            -   function: hfen_l2_norm_loss
                multiplier: 1.0
            -   function: hfen_l1_norm_loss
                multiplier: 1.0
            -   function: kspace_nmae_loss
                multiplier: 1.0
            -   function: kspace_nmse_loss
                multiplier: 1.0
validation:
    datasets:
        -   name: FastMRI
            transforms:
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4]
                    center_fractions: [0.08]
                scale_percentile: 0.995
                use_seed: true
            text_description: 4x  # Description for logging
        -   name: FastMRI
            transforms:
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                masking:
                    name: FastMRIEquispaced
                    accelerations: [8]
                    center_fractions: [0.04]
                scale_percentile: 0.995
                use_seed: true
            text_description: 8x  # Description for logging
        -   name: FastMRI
            transforms:
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                masking:
                    name: FastMRIEquispaced
                    accelerations: [16]
                    center_fractions: [0.02]
                scale_percentile: 0.995
                use_seed: true
            text_description: 16x  # Description for logging
    crop: header  # This sets the cropping for the DoIterationOutput
    metrics:  # These are obtained from direct.functionals
        - fastmri_psnr
        - fastmri_ssim
        - fastmri_nmse
    batch_size: 20
additional_models:
    sensitivity_model:
        model_name: unet.unet_2d.UnetModel2d
        in_channels: 2
        out_channels: 2
        num_filters: 16
        num_pool_layers: 4
        dropout_probability: 0.0
model:
    model_name: unet.unet_2d.Unet2d
    num_filters: 64
    image_initialization: sense
logging:
    tensorboard:
        num_images: 4
inference:
    crop: header
    batch_size: 5
    dataset:
        name: FastMRI
        transforms:
            use_seed: True
            masking:
                name: FastMRIEquispaced
                accelerations: [4]
                center_fractions: [0.08]
            cropping:
                crop: null
            sensitivity_map_estimation:
                estimate_sensitivity_maps: true
            normalization:
                scaling_key: masked_kspace
                scale_percentile: 0.995
        text_description: inference-4x  # Description for logging
