physics:
    forward_operator: fft2
    backward_operator: ifft2
training:
    datasets:
        -
            name: CMRxRecon
            kspace_context: time
            text_description: cine-training
            filenames_lists:
                - ../lists/246x512_cine_train.lst
            transforms:
                crop: reconstruction_size
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                random_flip_probability: 0.5
                masking:
                    name: FastMRIEquispaced
                    accelerations: [4, 8, 16]
                    center_fractions: [0.08, 0.04, 0.02]
                scale_percentile: 0.995
                use_seed: false
                delete_kspace: false
    batch_size: 1  # This is the batch size per GPU!
    optimizer: Adam
    lr: 0.002
    weight_decay: 0.0
    lr_step_size: 30000
    lr_gamma: 0.2
    lr_warmup_iter: 1000
    num_iterations: 500000
    gradient_steps: 1
    gradient_clipping: 0.0
    gradient_debug: false
    checkpointer:
        checkpoint_steps: 2000
    validation_steps: 4000
    loss:
        crop: header
        losses:
            -   function: l1_loss
                multiplier: 1.0
            -   function: ssim_loss
                multiplier: 1.0
            -   function: hfen_l2_norm_loss
                multiplier: 1.0
            -   function: hfen_l1_norm_loss
                multiplier: 1.0
            -   function: kspace_nmae_loss
                multiplier: 1.0
            -   function: kspace_nmse_loss
                multiplier: 1.0
validation:
    datasets:
        -   name: CMRxRecon
            kspace_context: time
            filenames_lists:
                - ../lists/cine_val.lst
            transforms:
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                masking:
                    name: FastMRIEquispaced
                    accelerations: [8]
                    center_fractions: [0.04]
                scale_percentile: 0.995
                use_seed: true
            text_description: 8x  # Description for logging
        -   name: CMRxRecon
            kspace_context: time
            filenames_lists:
                - ../lists/cine_val.lst
            transforms:
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                masking:
                    name: FastMRIEquispaced
                    accelerations: [16]
                    center_fractions: [0.02]
                scale_percentile: 0.995
                use_seed: true
            text_description: 16x  # Description for logging
    crop: header  # This sets the cropping for the DoIterationOutput
    metrics:  # These are obtained from direct.functionals
        - fastmri_psnr
        - fastmri_ssim
        - fastmri_nmse
    batch_size: 20
model:
    model_name: vsharp.vsharp.VSharpNet3D
    num_steps: 10
    num_steps_dc_gd: 8
    image_init: SENSE
    no_parameter_sharing: true
    auxiliary_steps: -1
    unet_num_filters: 32
    unet_num_pool_layers: 4
    initializer_channels:
        - 32
        - 32
        - 64
        - 64
    initializer_dilations:
        - 1
        - 1
        - 2
        - 4
    initializer_multiscale: 1
additional_models:
    sensitivity_model_3d:
        model_name: unet.unet_2d.UnetModel3d
        in_channels: 2
        out_channels: 2
        num_filters: 32
        num_pool_layers: 4
        dropout_probability: 0
logging:
    tensorboard:
        num_images: 4
