physics:
  forward_operator: fft2(centered=False)
  backward_operator: ifft2(centered=False)
training:
  datasets:
    - name: FakeMRIBlobs
      sample_size: 4
      num_coils: 4
      spatial_shape: [4, 32, 32]
      seed: 0
      text_description: static-2d
      transforms:
        cropping:
          crop: null
        sensitivity_map_estimation:
          estimate_sensitivity_maps: true
        normalization:
          scaling_key: masked_kspace
        masking:
          name: FastMRIRandom
          accelerations: [4]
          center_fractions: [0.16]
          range_mode: discrete
          mode: static
        use_seed: false
  batch_size: 2
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  lr_step_size: 1000
  lr_gamma: 0.5
  lr_warmup_iter: 0
  num_iterations: 2
  validation_steps: 2
  gradient_steps: 1
  loss:
    crop: null
    losses:
      - function: l1_loss
        multiplier: 1.0
  checkpointer:
    checkpoint_steps: 100
  metrics:
    - fastmri_psnr
validation:
  datasets:
    - name: FakeMRIBlobs
      sample_size: 2
      num_coils: 4
      spatial_shape: [4, 32, 32]
      seed: 1
      text_description: static-2d-val
      transforms:
        cropping:
          crop: null
        sensitivity_map_estimation:
          estimate_sensitivity_maps: true
        normalization:
          scaling_key: masked_kspace
        masking:
          name: FastMRIRandom
          accelerations: [4]
          center_fractions: [0.16]
          range_mode: discrete
          mode: static
        use_seed: true
  batch_size: 2
  crop: null
  metrics:
    - fastmri_psnr
    - fastmri_ssim
model:
  model_name: unet.unet_2d.Unet2d
  num_filters: 8
  num_pool_layers: 2
  dropout_probability: 0.0
  image_initialization: SENSE
logging:
  tensorboard:
    num_images: 2
