model:
    model_name: recurrentvarnet.recurrentvarnet.RecurrentVarNet
    num_steps: 12
    recurrent_hidden_channels: 128
    recurrent_num_layers: 4
    initializer_initialization: sense
    learned_initializer: true
    initializer_channels:
        - 32
        - 32
        - 64
        - 64
    initializer_dilations:
        - 1
        - 1
        - 2
        - 4
    initializer_multiscale: 3
additional_models:
    sensitivity_model:
        model_name: unet.unet_2d.UnetModel2d
        in_channels: 2
        out_channels: 2
        num_filters: 8
        num_pool_layers: 4
        dropout_probability: 0.0
physics:
    forward_operator: fft2(centered=False)
    backward_operator: ifft2(centered=False)
inference:
    batch_size: 1
    dataset:
        name: CalgaryCampinas
        crop_outer_slices: true
        transforms:
            use_seed: true
            delete_kspace: false
            masking:
                name: CalgaryCampinas
                accelerations:
                    - 5
            cropping:
                image_center_crop: false
            sensitivity_map_estimation:
                estimate_sensitivity_maps: true
            normalization:
                scaling_key: masked_kspace
                scale_percentile: 0.99
