# This model is a reproduction with some small changes of our winning algorithm in the Calgary-Campinas challenge
# at MIDL2020. It has an improved sensitivity estimation and better metric logging capabilities based on DIRECT v0.2
# features.
physics:
    forward_operator: fft2(centered=False)
    backward_operator: ifft2(centered=False)
training:
    datasets:
        # Two datasets, only difference is the shape, so the data can be collated for larger batches
        -   name: FakeMRIBlobs
#            lists:
#                - ./train.lst
            sample_size: 20
            num_coils: 16
            spatial_shape: [32, 40]
            transforms:
                crop: null
                estimate_sensitivity_maps: true  # Estimate the sensitivity map on the ACS
                scaling_key: masked_kspace  # Compute the image normalization based on the masked_kspace maximum
                image_center_crop: false
                masking:
                    name: FastMRIRandom
                    accelerations: [5]
                    center_fractions: [0.2]
                    seed: [0]
            seed: 10
#            crop_outer_slices: true
    batch_size: 4  # This is the batch size per GPU!
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.0
    lr_step_size: 50000
    lr_gamma: 0.2
    lr_warmup_iter: 1000
    num_iterations: 100
    gradient_steps: 1
    gradient_clipping: 0.0
    gradient_debug: false
    checkpointer:
        checkpoint_steps: 500
    validation_steps: 2 # With batch size 4 and 4 GPUs this is about 7300 iterations, or ~1 epoch.
    loss:
        crop: null
        losses:
            -   function: l1_loss
                multiplier: 1.0
            -   function: ssim_loss
                multiplier: 1.0
validation:
    datasets:
        # Twice the same dataset but a different acceleration factor
        -   name: FakeMRIBlobs
#            lists:
#                - ./val.lst
            sample_size: 10
            num_coils: 16
            spatial_shape: [32, 40]
            transforms:
                crop: null
                estimate_sensitivity_maps: true
                scaling_key: masked_kspace
                masking:
                    name: FastMRIRandom
                    accelerations: [5]
                    center_fractions: [0.2]
                    seed: [0]
#            crop_outer_slices: true
            text_description: 5x  # Description for logging
            seed: 11
    batch_size: 4
    crop: null  # This sets the cropping for the DoIterationOutput
    metrics:  # These are obtained from direct.functionals
        - fastmri_psnr
        - fastmri_ssim
model:
    model_name: rim.rim.RIM
    hidden_channels: 32
    image_initialization: sense  # This uses the computed sensitivity map to create a zero-filled reconstruction
    length: 16
    depth: 2
    steps: 1
    no_parameter_sharing: false
    instance_norm: false
    dense_connect: false
    replication_padding: true
inference:
    batch_size: 4
    dataset:
        name:  FakeMRIBlobs
#        crop_outer_slices: true
        text_description: inference
        transforms:
            crop: null
            estimate_sensitivity_maps: true
            scaling_key: masked_kspace
