model:
  model_name: vsharp.vsharp.VSharpNet3D
  engine_name: null
  num_steps: 8
  num_steps_dc_gd: 6
  image_init: SENSE
  no_parameter_sharing: true
  auxiliary_steps: -1
  initializer_channels:
  - 32
  - 32
  - 64
  - 64
  initializer_dilations:
  - 1
  - 1
  - 2
  - 4
  initializer_multiscale: 1
  initializer_activation: PRELU
  unet_num_filters: 16
  unet_num_pool_layers: 4
  unet_dropout: 0.0
  unet_norm: false
additional_models:
  sampling_model:
    model_name: adaptive.policy.StraightThroughPolicy
    engine_name: null
    sampling_dimension: ONE_D
    st_slope: 10.0
    st_clamp: false
    use_softplus: true
    slope: 10.0
    fix_sign_leakage: true
    acceleration: null
    kspace_shape:
    - 512
    - 246
    num_layers: 1
    kspace_sampler: false
    sampler_detach_mask: false
    sampler_chans: 16
    sampler_num_pool_layers: 3
    sampler_fc_size: 128
    sampler_drop_prob: 0.0
    sampler_num_fc_layers: 3
    sampler_activation: LEAKY_RELU
    sampling_type: DYNAMIC_2D
    num_time_steps: 11
    num_slices: null
  sensitivity_model:
    model_name: unet.unet_2d.UnetModel2d
    engine_name: null
    in_channels: 2
    out_channels: 2
    num_filters: 16
    num_pool_layers: 4
    dropout_probability: 0.0
  registration_model:
    model_name: registration.registration.UnetRegistration2dModel
    engine_name: null
    warp_num_integration_steps: 2
    decoupled_training: true
    rec_loss_factor: 1.0
    reg_loss_factor: 1.0
    max_seq_len: 11
    unet_num_filters: 16
    unet_num_pool_layers: 4
    unet_dropout_probability: 0.0
    unet_normalized: true
physics:
  forward_operator: fft2
  backward_operator: ifft2
  use_noise_matrix: false
  noise_matrix_scaling: 1.0
training:
  datasets:
  - name: CMRxRecon
    kspace_context: time
    text_description: train-4x
    transforms:
      registration:
        registration: true
        registration_simulate_reference: FROM_KEY
        registration_simulate_reference_from_key_index: 6
        registration_estimate_displacement: false
      padding_eps: 0
      masking:
        name: FastMRIEquispaced
        mode: DYNAMIC
        accelerations:
        - 4.0327
        center_fractions:
        - 0.04
      use_seed: false
      delete_kspace: false
      delete_acs_mask: false
      use_acs_as_mask: true
      augmentation:
        pad:
        - 512
        - 246
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
      normalization:
        scaling_key: acs_kspace
        scale_percentile: 0.995
      random_augmentations:
        random_rotation_probability: 0
        random_flip_probability: 0
  - name: CMRxRecon
    kspace_context: time
    text_description: train-6x
    transforms:
      registration:
        registration: true
        registration_simulate_reference: FROM_KEY
        registration_simulate_reference_from_key_index: 6
        registration_estimate_displacement: false
      padding_eps: 0
      masking:
        name: FastMRIEquispaced
        mode: DYNAMIC
        accelerations:
        - 6
        center_fractions:
        - 0.04
      use_seed: false
      delete_kspace: false
      delete_acs_mask: false
      use_acs_as_mask: true
      augmentation:
        pad:
        - 512
        - 246
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
      normalization:
        scaling_key: acs_kspace
        scale_percentile: 0.995
      random_augmentations:
        random_rotation_probability: 0
        random_flip_probability: 0
  - name: CMRxRecon
    kspace_context: time
    text_description: train-8x
    transforms:
      registration:
        registration: true
        registration_simulate_reference: FROM_KEY
        registration_simulate_reference_from_key_index: 6
        registration_estimate_displacement: false
      padding_eps: 0
      masking:
        name: FastMRIEquispaced
        mode: DYNAMIC
        accelerations:
        - 8.2
        center_fractions:
        - 0.04
      use_seed: false
      delete_kspace: false
      delete_acs_mask: false
      use_acs_as_mask: true
      augmentation:
        pad:
        - 512
        - 246
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
      normalization:
        scaling_key: acs_kspace
        scale_percentile: 0.995
      random_augmentations:
        random_rotation_probability: 0
        random_flip_probability: 0
  model_checkpoint: null
  optimizer: Adam
  lr: 0.003
  weight_decay: 0.0
  batch_size: 1
  lr_step_size: 10000
  lr_gamma: 0.8
  lr_warmup_iter: 2000
  swa_start_iter: null
  num_iterations: 60001
  validation_steps: 4000
  gradient_steps: 1
  gradient_clipping: 0.0
  gradient_debug: false
  loss:
    crop: null
    losses:
    - function: l1_loss
      multiplier: 1
    - function: ssim_loss
      multiplier: 1
    - function: ssim_3d_loss
      multiplier: 1
  checkpointer:
    checkpoint_steps: 1000
  metrics: []
  regularizers: []
validation:
  datasets:
  - name: CMRxRecon
    kspace_context: time
    text_description: val-4x
    transforms:
      registration:
        registration: true
        registration_simulate_reference: FROM_KEY
        registration_simulate_reference_from_key_index: 6
        registration_estimate_displacement: false
      padding_eps: 0
      masking:
        name: FastMRIEquispaced
        mode: DYNAMIC
        accelerations:
        - 4.0327
        center_fractions:
        - 0.04
      use_seed: true
      delete_kspace: false
      delete_acs_mask: false
      use_acs_as_mask: true
      augmentation:
        pad:
        - 512
        - 246
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
      normalization:
        scaling_key: acs_kspace
        scale_percentile: 0.995
      random_augmentations:
        random_rotation_probability: 0
        random_flip_probability: 0
  - name: CMRxRecon
    kspace_context: time
    text_description: val-6x
    transforms:
      registration:
        registration: true
        registration_simulate_reference: FROM_KEY
        registration_simulate_reference_from_key_index: 6
        registration_estimate_displacement: false
      padding_eps: 0
      masking:
        name: FastMRIEquispaced
        mode: DYNAMIC
        accelerations:
        - 6
        center_fractions:
        - 0.04
      use_seed: true
      delete_kspace: false
      delete_acs_mask: false
      use_acs_as_mask: true
      augmentation:
        pad:
        - 512
        - 246
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
      normalization:
        scaling_key: acs_kspace
        scale_percentile: 0.995
      random_augmentations:
        random_rotation_probability: 0
        random_flip_probability: 0
  - name: CMRxRecon
    kspace_context: time
    text_description: val-8x
    transforms:
      registration:
        registration: true
        registration_simulate_reference: FROM_KEY
        registration_simulate_reference_from_key_index: 6
        registration_estimate_displacement: false
      padding_eps: 0
      masking:
        name: FastMRIEquispaced
        mode: DYNAMIC
        accelerations:
        - 8.2
        center_fractions:
        - 0.04
      use_seed: true
      delete_kspace: false
      delete_acs_mask: false
      use_acs_as_mask: true
      augmentation:
        pad:
        - 512
        - 246
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
      normalization:
        scaling_key: acs_kspace
        scale_percentile: 0.995
      random_augmentations:
        random_rotation_probability: 0
        random_flip_probability: 0
  batch_size: 1
  metrics:
  - fastmri_ssim
  - fastmri_psnr
  regularizers: []
  crop: null
inference:
  dataset:
    name: CMRxRecon
    transforms:
      masking:
        name: FastMRIEquispaced
        accelerations:
        - 5.0
        center_fractions:
        - 0.1
        mode: STATIC
        val_accelerations:
        - 5.0
        - 10.0
        val_center_fractions:
        - 0.1
        - 0.05
        range_mode: DISCRETE
      target_acceleration: null
      cropping:
        crop: null
        crop_type: uniform
        image_center_crop: false
      augmentation:
        rescale: null
        rescale_mode: NEAREST
        rescale_2d_if_3d: false
        pad: null
      random_augmentations:
        random_rotation_degrees:
        - -90
        - 90
        random_rotation_probability: 0.0
        random_flip_type: RANDOM
        random_flip_probability: 0.0
        random_reverse_probability: 0.0
      padding_eps: 0.001
      estimate_body_coil_image: false
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
        sensitivity_maps_type: RSS_ESTIMATE
        sensitivity_maps_espirit_threshold: 0.05
        sensitivity_maps_espirit_kernel_size: 6
        sensitivity_maps_espirit_crop: 0.95
        sensitivity_maps_espirit_max_iters: 30
        sensitivity_maps_gaussian: 0.7
      normalization:
        scaling_key: masked_kspace
        scale_percentile: 0.99
      use_acs_as_mask: false
      delete_acs_mask: true
      delete_kspace: true
      image_recon_type: RSS
      compress_coils: null
      pad_coils: null
      registration:
        registration: false
        registration_simulate_reference: null
        registration_simulate_elastic_sigma: 3.0
        registration_simulate_elastic_points: 3
        registration_simulate_elastic_rotate: 0.0
        registration_simulate_elastic_zoom: 0.0
        registration_estimate_displacement: true
        registration_simulate_reference_from_key_index: 0
        registration_moving_key: TARGET
        demons_filter_type: SYMMETRIC_FORCES
        demons_num_iterations: 100
        demons_smooth_displacement_field: true
        demons_standard_deviations: 1.5
        demons_intensity_difference_threshold: null
        demons_maximum_rms_error: null
      use_seed: true
      transforms_type: SUPERVISED
      mask_split_ratio:
      - 0.4
      mask_split_acs_region:
      - 0
      - 0
      mask_split_keep_acs: false
      mask_split_type: GAUSSIAN
      mask_split_gaussian_std: 3.0
      mask_split_half_direction: VERTICAL
    text_description: null
  batch_size: 1
  metrics: []
  crop: null
logging:
  log_as_image: null
  tensorboard:
    num_images: 4
