model:
  model_name: vsharp.vsharp.VSharpNet
  num_steps: 12
  num_steps_dc_gd: 10
  image_init: SENSE
  no_parameter_sharing: true
  auxiliary_steps: -1
  image_model_architecture: UNET
  initializer_channels: [32, 32, 64, 64]
  initializer_dilations: [1, 1, 2, 4]
  initializer_multiscale: 1
  initializer_activation: PRELU
  image_unet_num_filters: 32
  image_unet_num_pool_layers: 4
  image_unet_dropout: 0.0
  image_unet_conv_out_bias: true
additional_models:
  sensitivity_model:
    model_name: unet.unet_2d.UnetModel2d
    in_channels: 2
    out_channels: 2
    num_filters: 32
    num_pool_layers: 4
    dropout_probability: 0.0
physics:
  forward_operator: fft2
  backward_operator: ifft2
inference:
  batch_size: 1
  crop: null
  metrics:
    - fastmri_ssim
    - fastmri_psnr
    - fastmri_nmse
  dataset:
    name: CMRxRecon
    text_description: cardiac_4x_equispaced
    transforms:
      use_seed: true
      delete_kspace: false
      masking:
        name: FastMRIEquispaced
        accelerations: [4]
        # accelerations: [2]
        # center_fractions: [0.1]
        # accelerations: [6]
        # center_fractions: [0.06]
        # accelerations: [8]
        center_fractions: [0.08]
      cropping:
        crop: null
        image_center_crop: false
      sensitivity_map_estimation:
        estimate_sensitivity_maps: true
      normalization:
        scaling_key: masked_kspace
        scale_percentile: 0.995
